# DATASOURCE
spring:
  application:
    name: bvss-es6-api-estoque

  datasource:
    url: "jdbc:h2:mem:db-bvss"
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa.database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 5000
  servlet:
    context-path: /bvss-es6-api-estoque

# H2
h2:
  console:
    enabled: true
    path: /h2-console

#spring:
#  application:
#    name: bvss-es6-api-estoque
#  cloud:
#    config:
#      server:
#        bootstrap: true
#        git:
#          uri: https://github.com/brunovschettini/bvss-config-server.git
#          skipSslValidation: true
#          search-paths: bvss-es6-api-estoque
#          username: 
#          password: 