# DATASOURCE
spring:
    datasource:
        url: "jdbc:h2:mem:db-bvss"
        driverClassName: org.h2.Driver
        username: sa
        password: password
    jpa.database-platform: org.hibernate.dialect.H2Dialect

# H2
h2:
    console:
        enabled: true
        path: /h2-console
